[book]
authors = ["Deref Patterns Project Group Members"]
language = "en"
multilingual = false
src = "."
title = "Deref Patterns Project Group"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/project-deref-patterns"
